# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipperModel',
            fields=[
                ('model_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('max_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('current_weight', models.FloatField()),
                ('vehicle_overweight', models.FloatField()),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TipperModel')),
            ],
        ),
    ]
